version: "3.4"
services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP= true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .\config.json:/config.json
    command: --interval 5
