apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-node
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/edwardlawzy/ArgoCD_Deployment.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true