#####################################################################################
### ArgoCD doesn't use this file, It uses the files in the ArgoCD_Deployment repo ###
###                  This file is kept for visibility only                        ###
#####################################################################################

apiVersion: v1
kind: Service
metadata:
  name: todo-app-node-service
spec:
  selector:
    app: todo-app-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: NodePort # Or LoadBalancer if on cloud, but NodePort for VM
