
---
- name: Configure Linux VM and Install Docker
  hosts: DockerServers
  become: yes 

  tasks:
    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update yum/dnf cache and upgrade packages
      ansible.builtin.yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install dependencies for Docker
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker Engine, Docker CLI, containerd.io, Docker Buildx, Docker Compose plugin
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Add current user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Copy _vm.env to VM
      ansible.builtin.copy:
         src: /mnt/d/Data/DevOps/FortStark_Assessment/Todo-List-nodejs/_vm.env
         dest: /home/fortstark/.env

############################################################################################################################         
################################################        USING COMPOSE       ################################################
############################################################################################################################         

    - name: Copy docker-compose file to VM
      ansible.builtin.copy:
         src: /mnt/d/Data/DevOps/FortStark_Assessment/Todo-List-nodejs/docker-compose.yml
         dest: /home/fortstark/docker-compose.yml

    - name: Run APP Docker Container
      ansible.builtin.command:
        cmd: docker compose up -d
 
    - name: Copy WatchTower folder
      ansible.builtin.copy:
       src: /mnt/d/Data/DevOps/FortStark_Assessment/Todo-List-nodejs/watchtower
       dest: /home/fortstark/

    - name: Run WatchTower Container
      ansible.builtin.command:
        cmd: docker run -d --name watchtower -v /var/run/docker.sock:/var/run/docker.sock -v ./watchtower/config.json:/config.json containrrr/watchtower --schedule "5 * * * * *"  --cleanup

